services:
  # setup postgres source database
  source_postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - cdc_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    command: # automatically set the wal_level to logical to get CDC from the transaction logs of the db
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - ./db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  # setup pgadmin for easier management of db
  pg_admin:
    image: dpage/pgadmin4:latest
    ports:
      - "8000:80"
    networks:
      - cdc_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./pg_admin_config/servers.json:/pgadmin4/servers.json # automatically creates the server connection to the postgres db
    depends_on:
      - source_postgres

  # launch zookeeper to manage kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    networks:
      - cdc_network
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    depends_on:
      - source_postgres

  # launch kafka
  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    networks:
      - cdc_network
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

  # launch debezium as the connector for the postgres db to kafka for cdc streaming
  debezium:
    image: debezium/connect:1.4
    networks:
      - cdc_network
    environment:
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: io.confluent.connect.avro.AvroConverter
      VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
    depends_on:
      - kafka
    ports:
      - 8083:8083

  # setup schema registry to ensure data structure consistency when streaming to kafka
  schema-registry:
    image: confluentinc/cp-schema-registry:5.5.3
    networks:
      - cdc_network
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://schema-registry:8081,http://localhost:8081
    ports:
      - 8081:8081
    depends_on:
      - zookeeper
      - kafka
  
  # gui to manage and setup clusters/topics for kafka
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    networks:
      - cdc_network
    restart: always
    ports:
      - "9090:9000"
    depends_on:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null 

  trino:
    hostname: trino
    image: 'trinodb/trino:351'
    ports:
      - '8086:8080'
    volumes:
      - ./etc:/usr/lib/trino/etc:ro
    networks:
      - cdc_network

  mariadb:
    hostname: mariadb
    image: mariadb:10.5.8
    ports:
      - 3336:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - cdc_network

  hive-metastore:
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - cdc_network

  minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - cdc_network

volumes:
  minio-data:
    driver: local


networks:
  cdc_network:
    driver: bridge